@startuml Get All Reservations (GET)

header Restaurant Reservation Sequence Diagram
footer Page %page% of %lastpage%
title "Get All Reservations (GET)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:reservations" as routerReservations
participant "<<controllers>>\n:reservations" as controllersReservations
participant "<<model>>\n:Reservation" as modelReservation
database "<<MongoDB>>\n:reservations" as ReservationsDatabase

client->server ++: req.get('/api/v1/reservations', protect)
server->routerReservations ++: app.use('/api/v1/reservations', reservations)
routerReservations -> controllersReservations ++: getReservations()
controllersReservations->modelReservation ++: find(query)
modelReservation -> ReservationsDatabase ++: ReservationSchema
ReservationsDatabase --> modelReservation --: reservations
modelReservation --> controllersReservations --: reservations
controllersReservations->client --: response

@enduml
